# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChesterNative' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ChesterNative

  pod 'FirebaseMessaging', '2.0.0'

  target 'ChesterNativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
